language: python
branches:
  only:
  - source
install:
- pip install pelican ghp-import markdown
script:
- make clean html travis_github
env:
  global:
    secure: "q9y8z/Il0+Os7wuVM3hpfnoZC1KrCwEcog/Uzke1b7rFq/zggxtGOfVzBOJaTikaCGHlSGLXB2P6Tve/ZlwJDPhL7hiiVQORRaw2VM5MiDd0bBZ6ypaQyKI7UPg7AAGgs3hHkbc52f/dm4I3V/pmBCmAP+29sVwtynyVA64v0qU+yWxUnaIkvBNamGe4scfnGi/fEi2ciD5PfMNLGVHeE5ILFfbWBldLyEIQCrD2QXYKHnOExy0Tq4fvkoCvf9D8iq2umGb8P+K2uxBIVzz0VYbuXy/CkICMY4Sc+hD+fUdLfgtXj73rjVw2wngoxoBua3voosIN47qvWqJxJSNDkXc34ECJ+rJG7xGkAFkKqRZSdQinqhdSsBBR63J+gIRHiKTo9eRmjQTnl+g1bNfI6FgT/VIFARNx+Wb9OQPNJZQO8K6R3YfYTZy/DoyHAVlxI9gjET+hSCWVo46TOWbK5i7UipLm6kMcX6pL/5nOoWFSnGVSQvFfK9BsbNekAXeiL85lPh2vf9pb1FSG3DV8LKk2jH3pksdCmDNKDa3A6e7R8LDAgt53n1h3kPo/5fmOBeFfxEEuea4poDIS6F1vgJ2+8RleNhgu6FhTPpWktCiEvfY7t5suWBbGuPmadOETk2jPP8gdvmaJPWsLJA/XPUUdcftCbnBXnBGbXj1gu5w="
